import type { Metadata } from "next";
import Navbar from '@/components/navbar'; 
import Footer from '@/components/Footer';
import '@/assets/styles/globals.css';
import AuthProvider from "@/components/AuthProvider";
import {UnreadMessageProvider} from '@/context/messageReadContext'
import { ToastContainer } from 'react-toastify';


export const metadata: Metadata = {
  title: "property dekho",
  description: "Generated by Kritul",
  keywords: 'rental, property, real estate',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body >
        <AuthProvider>
          <UnreadMessageProvider>
            <ToastContainer/>
            <Navbar/>
            <main>{children}</main>
            <Footer/>
          </UnreadMessageProvider>
        </AuthProvider>
      </body>
    </html>
    
  );
}
